### ISSUE TITLE
非常好用，能做个哔哩哔哩版本的吗？

### ISSUE THREAD

**Issue by yyw6853486** [zhzLuke96/ytp-rotate#1]
油猴上面有很多功能复杂的html5视频脚本，但是快捷键太多会和别的插件冲突， 还是您的旋转插件方便好用，能不能兼容下哔哩哔哩呢？上面手机竖版视频比较多，有了这个就能在电脑上方便的观看了！:)

**Comment by zhzLuke96** [comment]
感谢反馈，兼容其他视频平台也考虑过，今年有空的话会搞下看看 👻

----

b站这边好用的油猴插件还是挺多的，比如这个
[https://github.com/Xmader/bilitwin](https://github.com/Xmader/bilitwin)
bilibili有插件需求的话可以考虑提给他 😉
