### ISSUE TITLE
旋转不了画面。

### ISSUE THREAD

**Issue by kitkw** [zhzLuke96/ytp-rotate#4]
更新了！但旋转不了画面其他功能也是无效的（点击没有反应），右键也没有出来选项。之前老版是正常的。
![image](https://github.com/zhzLuke96/ytp-rotate/assets/31963066/69fa170d-7a60-4d5a-a744-296e70264ac7)

**Comment by zhzLuke96** [comment]
是特别的视频页面会这样吗？还是所有页面都是？
可以提供下视频链接，或者提供浏览器控制台中和本脚本相关的错误输出吗

也可以检查一下是否出现 重复安装 脚本的情况
因为一些greasyfork配置问题可能导致新旧版本重复安装，清除不需要的即可


如果需要回退版本点击这个链接（此版本已不维护）：
https://github.com/zhzLuke96/ytp-rotate/raw/master/ytp-rotate-v1.user.js

**Comment by zhzLuke96** [comment]
现在新版本应该解决了，是因为油管更新了防ads block策略，播放器一些逻辑变了，现在兼容了
