### ISSUE TITLE
后台打开视频时出现白边问题

### ISSUE THREAD

**Issue by LidoCKT** [zhzLuke96/ytp-rotate#5]
![image](https://github.com/zhzLuke96/ytp-rotate/assets/24887103/092a1f0b-6dea-4de6-bca4-ce8136e56ad1)

在开启脚本的情况下，通过鼠标中键点击在后台打开视频，再切换到该视频时，如上图所示视频一周有白边。
手动暂停再播放或者全屏等操作后白边消失。

**Comment by zhzLuke96** [comment]
没有复现出来额

在你发这个视频页测了，在我的环境没有出现这种情况

是chrome吗？什么操作系统，版本号多少，屏幕宽高，提供更多信息方便排查

**Comment by zhzLuke96** [comment]
v2.4 问题已解决

**Comment by mx4994** [comment]
chroem：120.0.6099.110  系统：Windows10 19045.3031 显示器：27寸4K 150%缩放
暴力猴2.16.0 脚本2.4最新

一般在油管首页点击视频进去不会出问题，但是通过视频链接进去有一定概率，还有就是视频已打开，页面刷新有一定概率。
https://www.youtube.com/watch?v=-z_RHaJ72zE 这个视频链接直接进或者页面刷新可以~~稳定~~复现。怎么抓日志，不会搞
![image](https://github.com/zhzLuke96/ytp-rotate/assets/52325833/2e4736ca-a722-455b-80e6-d2a85aa2a46b)

**Comment by zhzLuke96** [comment]
> chroem：120.0.6099.110 系统：Windows10 19045.3031 显示器：27寸4K 150%缩放 暴力猴2.16.0 脚本2.4最新
> 
> 一般在油管首页点击视频进去不会出问题，但是通过视频链接进去有一定概率，还有就是视频已打开，页面刷新有一定概率。 https://www.youtube.com/watch?v=-z_RHaJ72zE 这个视频链接直接进或者页面刷新可以~稳定~复现。怎么抓日志，不会搞 ![image](https://private-user-images.githubusercontent.com/52325833/291259369-2e4736ca-a722-455b-80e6-d2a85aa2a46b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODczMTUsIm5iZiI6MTcwMzA4NzAxNSwicGF0aCI6Ii81MjMyNTgzMy8yOTEyNTkzNjktMmU0NzM2Y2EtYTcyMi00NTViLTgwZTYtZDJhODVhYTJhNDZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDE1NDMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZWNkYmJhN2UyYjg3NDRjZWQ1ZGZmYzQyMzY1MzAyN2NmNTRhZjgwYzZhMGIxN2JjYmJkMDliNzMyNDFkMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tdVgigLQhIyJ4K5dn15r97MWSenLMNdNoIDdOHJ1VvU)

感谢反馈，这个问题 v2.5 应该修好了
