### ISSUE TITLE
在Edge下无法使用

### ISSUE THREAD

**Issue by LidoCKT** [zhzLuke96/ytp-rotate#7]
大概最近几天发现在Edge下无法使用 Chrome下正常

使用如下环境

Microsoft Edge
版本 126.0.2592.13 (正式版本) stable应用，beta频道 (64 位)

暴力猴 2.18.0

**Comment by zhzLuke96** [comment]
在stable channel版本测试没复现bug

不准备适配beta版本，如果126出stable还有问题的话再提
